/* Max 8/9 [js]. Oscillators are standard cycle~ objects in the main patch. */
autowatch = 1;
inlets = 1;
outlets = 4;
include("phonon_data.js");
include("phonon_core.js");
var state = Phonon.defaults();

function setui(name, value) {
    var obj = this.patcher.getnamed(name);
    if (obj) { obj.message("set", value); }
}
setui.local = 1;
function refresh() {
    var result = Phonon.calculate(state);
    state.angle = result.angle;
    setui("angle", state.angle);
    setui("angle_slider", state.angle*10);
    for (var i=0; i<12; i++) {
        var v = result.voices[i];
        outlet(0, [i+1, v.oscillatorHz, v.amplitude, state.glide]);
    }
    outlet(3, result.reference);
    outlet(2, ["state", state.angle, state.mode, state.mapping,
               state.low, state.high, state.root, state.octaves, state.partner,
               state.samplerate].concat(state.gains));
    var msg = result.active + " voices audible; " + result.outOfBand + " outside range.";
    if (state.mode) { msg += " A-ZA reference " + result.reference.toFixed(2) + " Hz."; }
    else { msg += state.mapping===0 ? " Common frequency scale preserves energy ratios." : " Range mapping reshapes energy ratios."; }
    if (state.angle<6 || state.angle>54) { msg += " Near alignment: model extension."; }
    outlet(1, msg);
}
refresh.local = 1;
function bang() { refresh(); }
function init() {
    state=Phonon.defaults();
    var sr=this.patcher.getnamed("sr_query");
    if (sr) { sr.message("bang"); }
    var pairs=[['mode',0],['mapping',0],['low',30],['high',4000],['root',110],
               ['octaves',1],['partner',0],['glide',60],['master',0.15],['play',0]];
    for(var i=0;i<pairs.length;i++) {setui(pairs[i][0],pairs[i][1]);}
    for(i=0;i<6;i++){setui("gain"+i,1);}
    var masterObj=this.patcher.getnamed("master_message");
    if(masterObj){masterObj.message(0.15);}
    var playObj=this.patcher.getnamed("play_message");
    if(playObj){playObj.message(0);}
    refresh();
}
function angle(v) { if(isFinite(v)){state.angle=Phonon.clamp(v,0,60);refresh();} }
function mode(v) { state.mode=Phonon.clamp(Math.round(v),0,2);refresh(); }
function mapping(v) { state.mapping=Phonon.clamp(Math.round(v),0,2);refresh(); }
function low(v) {
    if(!isFinite(v)){return;}
    state.low=Phonon.clamp(v,20,state.high-1);setui("low",state.low);refresh();
}
function high(v) {
    if(!isFinite(v)){return;}
    state.high=Phonon.clamp(v,state.low+1,20000);setui("high",state.high);refresh();
}
function root(v) { if(isFinite(v)){state.root=Phonon.clamp(v,20,2000);refresh();} }
function octaves(v) { state.octaves=Phonon.clamp(Math.round(v),1,5);refresh(); }
function partner(v) { state.partner=Phonon.clamp(v,0,1);refresh(); }
function glide(v) { state.glide=Phonon.clamp(v,5,2000);refresh(); }
function samplerate(v) { if(isFinite(v)&&v>=8000){state.samplerate=v;refresh();} }
function gain(branch, v) {
    if(branch>=0&&branch<6&&isFinite(v)){state.gains[branch]=Phonon.clamp(v,0,1);refresh();}
}
function step(v) { angle(Math.round(state.angle)+v); }
function dump() {
    post("PHONON_STATE " + JSON.stringify({settings:state,result:Phonon.calculate(state)}) + "\n");
}
function exportscale(path) {
    if(state.mode===0){outlet(1,"Choose a temperament mode before exporting a scale.");return;}
    var file = new File(path,"write","TEXT");
    if(!file.isopen){outlet(1,"Could not write scale file.");return;}
    var cents=Phonon.scale(state.mode,state.octaves);
    file.eof=0;
    file.writeline("! Graphene phonon temperament; generated by Graphene_Phonons.maxpat");
    file.writeline("! Birkbeck et al. 2025 Fig.1f model overlay; see README.md");
    file.writeline((state.mode===2?"ZA-shaped (90% curve + 10% equal)":"Equal")+" 60 steps over "+state.octaves+" octaves");
    file.writeline("60");
    file.writeline("!");
    for(var i=1;i<=60;i++){file.writeline(cents[i].toFixed(8));}
    file.close();
    outlet(1,"Saved scale. 0 cents is implicit; degree 60 is the period.");
}
